version: "3"
services:
  madup_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: madup_backend
    ports:
      - 8000:8000
    depends_on:
      - madup_db
    environment:
      - DJANGO_DEBUG=TRUE
      - DJANGO_DB_NAME=madup
    command: 
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/
    restart: always
    entrypoint: ./wait-for-it.sh madup_db:3306 --

  madup_db:
    image: mysql:5.7.16
    container_name: madup_db
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOST: "${MYSQL_HOST}"
    ports:
      - 3306:3306